apiVersion: v1
kind: Service
metadata:
  name: {{ template "divvycloud.name" . }}-interfaceserver
  labels:
    app: {{ template "divvycloud.name" . }}-interfaceserver
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
  {{ if .Values.internalLoadBalancer }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  {{ end }}
spec:
  type:  LoadBalancer
  ports:
    - port: {{ .Values.interfaceserver_port | default "8001" }}
  selector:
    app: {{ template "divvycloud.name" . }}-interfaceserver
    release: {{ .Release.Name }}

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-interfaceserver
  labels:
    app: {{ template "divvycloud.name" . }}-interfaceserver
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ if .Values.replicaCounts  }}  {{ .Values.replicaCounts.interfaceservers | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-interfaceserver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-interfaceserver
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: ['divvyinterfaceserver','-n']
          livenessProbe:
            httpGet:
              path: /Status
              port: 8001
          readinessProbe:
            httpGet:
              path: /Status
              port: 8001
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
