apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-interfaceserver
  labels:
    app: {{ template "divvycloud.name" . }}-interfaceserver
    chart: {{ template "divvycloud.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ if .Values.replicaCounts  }}  {{ .Values.replicaCounts.interfaceservers | default 2 }} {{ else }} 2 {{ end }}
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-interfaceserver
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-interfaceserver
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.imageName }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          {{ if eq .Values.enablePlugins true }}
          command: ['sh','/scripts/entrypoint.sh']
          {{ end }}
          args: ['divvycloud','webserver']
          livenessProbe:
            httpGet:
              path: /Status
              port: 8001
          readinessProbe:
            httpGet:
              path: /Status
              port: 8001
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ template "divvycloud.name" . }}-secret 
          volumeMounts:
          - name: entrypoint
            mountPath: /scripts/
          {{ if eq .Values.enablePlugins true }}
          - name: plugins
            mountPath: /tmpPlugins/
            readOnly: true
          {{ end }}
      {{ if .Values.imagePullSecret }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
      {{ end }}
      volumes:
      {{ if eq .Values.enablePlugins true }}
      - name: plugins
        secret:
            secretName: divvycloud-plugins
      {{ end }}
      - name: entrypoint
        secret:
            secretName: {{ template "divvycloud.name" . }}-entrypoint
