
{{ if .Values.pvcEnabled }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: divvycloud-mysql-pvc
  labels:
    app: mysql
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storageSize | default "30Gi" }}
{{ end  }}

{{ if eq .Values.useExternalDb false }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "divvycloud.name" . }}-mysql
spec:
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-mysql
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-mysql
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: {{ .Values.mysqlInstance | default "divvycloud/quickstart-db" }}
        args:
          - "--ignore-db-dir=lost+found --datadir=/var/lib/mysq/data"
        envFrom:
          - secretRef:
              name: {{ template "divvycloud.name" . }}-secret 
        name: {{ template "divvycloud.name" . }}-mysql
        ports:
        - containerPort: 3306
    {{ if .Values.pvcEnabled }}
        volumeMounts:
        - name: divvycloud-mysql-pvc
          mountPath: /var/lib/mysql
          subPath: data
      volumes: 
      - name: divvycloud-mysql-pvc
    {{ end }}
{{ end }}
