

---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name : divvycloud
  name: {{ template "divvycloud.name" . }}-redis
spec:
  selector:
    matchLabels:
      app: {{ template "divvycloud.name" . }}-redis
      release: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "divvycloud.name" . }}-redis
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: redis
        name: {{ template "divvycloud.name" . }}-redis
        ports:
        - containerPort: 6379

