{{- $mysql_host := (printf "%s-mysql" (include "divvycloud.name" .)) -}}
{{- $redis_host := (printf "%s-redis" (include "divvycloud.name" .)) -}}
{{- $random_root_password := (printf "%s" (randAlpha 16)) -}}
{{- $random_password := (printf "%s" (randAlpha 16)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "divvycloud.name" . }}-secret
  labels:
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
data:


  {{- if .Values.database_host }} 
  {{ else }}
  MYSQL_DATABASE : {{ "divvy" | b64enc }}
  MYSQL_ROOT_PASSWORD: {{ .Values.databaseRootPassword | default $random_root_password | b64enc }}
  MYSQL_USER: {{ .Values.databaseUser | default "divvy" | b64enc }}
  MYSQL_PASSWORD : {{ .Values.databasePassword | default $random_password | b64enc }}
  {{- end }}

  DIVVY_DB_HOST: {{ $mysql_host | b64enc }}
  DIVVY_DB_PORT: {{  "3306" | b64enc }}


  DIVVY_DB_USER : {{ .Values.databaseUser | default "divvy" | b64enc }}
  DIVVY_DB_PASSWORD : {{ .Values.databasePassword | default $random_password | b64enc }}
  DIVVY_DB_NAME : {{ .Values.databaseName | default "divvy" | b64enc }}

  DIVVY_SECRET_DB_HOST: {{ $mysql_host | b64enc }}
  DIVVY_SECRET_DB_PORT: {{  "3306" | b64enc }}


  DIVVY_SECRET_DB_USER : {{ .Values.databaseUser | default "divvy" | b64enc }}
  DIVVY_SECRET_DB_PASSWORD : {{ .Values.databasePassword | default $random_password | b64enc }}
  DIVVY_SECRET_DB_NAME : {{ .Values.databaseName | default "divvykeys" | b64enc }}

  {{ if .Values.useExternalRedis }}
  DIVVY_REDIS_HOST : {{  .Values.redisHost | b64enc }}
  {{ else }}
  DIVVY_REDIS_HOST : {{ $redis_host  | b64enc }}
  {{ end }}

  {{if .Values.httpProxy }}
  http_proxy: {{ .Values.httpProxy | b64enc }}
  {{end}}

  {{if .Values.httpsProxy }}
  https_proxy: {{ .Values.httpsProxy | b64enc }}
  {{end}}

  {{if .Values.noProxy}}
  no_proxy: {{ .Values.noProxy | b64enc }}
  {{end}}


---
apiVersion: v1
kind: Secret
metadata:
  name: divvycloud-plugins
  labels:
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
data:
  nodata: {{ print "nodata" | b64enc }}

---
{{ if .Values.cloudSQLInstanceName }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-db-credentials
  labels:
    app.kubernetes.io/name: {{ template "divvycloud.name" . }}
data:
  username: {{ .Values.databaseUser | b64enc }}
  password: {{ .Values.databasePassword | b64enc }}
{{end}}
